name = "Juan "
print (name)
name.upper()
print (name)
name = name.capitalize()
print (name)
name = name.strip()
print (name)
name.lower()
print (name)
name.replace('u','a')
print (name)
print (name[3])
print(len(name))